### ISSUE TITLE
newUser.hbs Error 500

### ISSUE THREAD

**Issue by ElectronHarvester** [ElectronHarvester/WPS_Web#13]
Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at validUser (C:\Apps\ElectronHarvester\WPS_Web\server\lib\validations.js:21:24)
    at validateUserRenderError (C:\Apps\ElectronHarvester\WPS_Web\server\routes\user.js:118:6)
    at C:\Apps\ElectronHarvester\WPS_Web\server\routes\user.js:58:3
    at Layer.handle [as handle_request] (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:312:13)
    at C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Apps\ElectronHarvester\WPS_Web\server\node_modules\express\lib\router\index.js:330:12)

**Comment by ElectronHarvester** [comment]
Error 500 when 'typeof user.password == 'string' &&' is in the validations.js doc. The above error is displayed when removed. Acts like the password is not being set.

**Comment by ElectronHarvester** [comment]
Working now.... Will check in again as EditUser does throws error.
